name: Compilar ProxyPin

on:
  workflow_dispatch: # Isso cria um botão pra você rodar quando quiser

jobs:
  build:
    name: Compilar APK
    runs-on: ubuntu-latest # A "VPS" do GitHub

    steps:
      - name: 1. Baixar o código do seu repositório
        uses: actions/checkout@v4

      - name: 2. Configurar o Java (Necessário para Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 3. Configurar o Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 4. Baixar as dependências do app
        run: flutter pub get

      - name: 5. Compilar o APK
        run: flutter build apk --release

      - name: 6. Salvar o APK gerado pra você baixar
        uses: actions/upload-artifact@v4
        with:
          name: ProxyPin-PT-BR-APK
          path: build/app/outputs/flutter-apk/app-release.apk
